In [2]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.datasets import load_iris

from EDA import edaMLOpt

## Load dataset

In [3]:
iris_df = load_iris(as_frame=True)
print("Dataset n of samples: ", len(iris_df["frame"]))
dataframe = iris_df["frame"].sample(frac=1)
dataframe.head()

Dataset n of samples:  150


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
137                6.4               3.1                5.5               1.8   
18                 5.7               3.8                1.7               0.3   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
104                6.5               3.0                5.8               2.2   

     target  
137       2  
18        0  
130       2  
131       2  
104       2

In [4]:
X = dataframe.iloc[:,:-1].values
Y = dataframe.iloc[:,-1].values
print(X[:4], '\n', Y[:10])

[[6.4 3.1 5.5 1.8]
 [5.7 3.8 1.7 0.3]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]] 
 [2 0 2 2 2 1 0 1 1 0]


## Define Starting hyperparameter grid

In [5]:
#Set starting grid Point
grid = {
    "n_estimators" : np.linspace(10, 100, dtype=int),
    #"criterion" : ["gini", "entropy"],
    "min_samples_split" : np.linspace(2, 100, dtype=int),
    "min_samples_leaf": np.linspace(2, 100, dtype=int),
    "max_features": np.linspace(0.3, 1.0, num=7, dtype=float),   
}

# Minimums for random forest hyperparameters. Same key names as grid
mins_rf = {
    "n_estimators" : 1,
    "min_samples_split" : 2,
    "min_samples_leaf" : 2,
    "max_features" : 0.1
}

dtypes = [int, int, int, float]

## Rock and roll ...

In [6]:
params = edaMLOpt(X,Y, grid=grid, mins_dict=mins_rf, dtypes=dtypes,
                  folds=3, nR=20, nN=4, nIterNum=4, 
                  edaThreshold=0.01)

Start EDA optimization for camera calibration
==== generation 0: ====
fitting fold 0 of individual 0
fitting fold 1 of individual 0
fitting fold 2 of individual 0
Accuracy for ind. 0 -> 0.9466666666666667
fitting fold 0 of individual 1
fitting fold 1 of individual 1
fitting fold 2 of individual 1
Accuracy for ind. 1 -> 0.9533333333333333
fitting fold 0 of individual 2
fitting fold 1 of individual 2
fitting fold 2 of individual 2
Accuracy for ind. 2 -> 0.2933333333333334
fitting fold 0 of individual 3
fitting fold 1 of individual 3
fitting fold 2 of individual 3
Accuracy for ind. 3 -> 0.9466666666666667
fitting fold 0 of individual 4
fitting fold 1 of individual 4
fitting fold 2 of individual 4
Accuracy for ind. 4 -> 0.2866666666666667
fitting fold 0 of individual 5
fitting fold 1 of individual 5
fitting fold 2 of individual 5
Accuracy for ind. 5 -> 0.2866666666666667
25%%...
fitting fold 0 of individual 6
fitting fold 1 of individual 6
fitting fold 2 of individual 6
Accuracy for ind. 6